service: github-backup-aws-s3-service
provider:
  name: aws
  runtime: nodejs12.x
  region: ap-southeast-1
  profile: tooling
  timeout: 600
functions:
  runBackup:
    handler: handler.runBackup
    events:
      - schedule: cron(0 3 * * ? *) # 3am everyday
    # events:
    #   - schedule: ${opt:schedule-expression} # http://docs.aws.amazon.com/AmazonCloudWatch/latest/events/ScheduledEvents.html
